import { News } from './news';

export const NEWSPERSONAL: News[] = [
    new News(19, 'Los Ángeles cancela el Día de Colón', 'La Historia, según el lado del Atlántico donde se relate, se antoja muy distinta. Unos lo entienden como una causa gloriosa de expansión territorial y de dominio, y otros como uno de los mayores genocidios registrados hasta la fecha...', 'La Historia, según el lado del Atlántico donde se relate, se antoja muy distinta. Unos lo entienden como una causa gloriosa de expansión territorial y de dominio, y otros como uno de los mayores genocidios registrados hasta la fecha, una masacre para los pueblos indígenas de América ante la llegada del conquistador europeo.\n' +
        '\n' +
        'El miércoles se impuso la segunda versión de los hechos en la segunda ciudad de Estados Unidos, Los Angeles. A partir de ahora, el 12 de octubre ya no estará dedicado a la figura de Cristobal Colón, el italiano enviado por los Reyes Católicos para descubrir nuevos mundos, sino a los indígenas que perdieron la vida ante la llegada de las huestes españolas en distintas partes de América.\n' +
        '\n' +
        'El consejo municipal de Los Angeles decidió, por 14 votos a favor y uno en contra, que el segundo lunes de octubre esté marcado en el calendario como el Día de las Gentes Indígenas y no como el Día de Colón (Columbus Day), como era hasta ahora en la ciudad californiana al igual que en el resto del país.\n' +
        '\n' +
        'Es una batalla moral e intelectual que se venía librando desde hacía muchos años en Los Angeles. De hecho, una de las urbes más avanzadas en estas lides, Berkeley, al norte del estado, tomó esta misma decisión hace 25 años, considerando que lo sucedido en América durante el siglo XV y XVI había sido lo suficientemente sangrante como para no ensalzar la figura de uno de sus valedores.\n' +
        '\n' +
        'La votación fue la culminación de un acalorado debate entre los italoamericanos, defensores del legado de sus antepasados, y los de sangre latina -y anglosajona también- que esgrimían la masacre y las violaciones cometidas con la llegada de los españoles como suficiente motivo para cambiar la denominación de la fiesta. Joe Buscaino, concejal de origen italiano, viendo la causa perdida, sugirió dejar el festivo en un "Día de la Diversidad", pero nadie le compró la idea.\n' +
        '\n' +
        'Al final se impuso el concepto de "desmantelar una celebración del genocidio de las gentes indígenas por parte del estado" y evitar que los indígenas tuvieran que celebrar cualquier otro día. "Eso sería una mayor injusticia", afirmó Chrissie Castro, miembro de la Comisión de Indios Americanos del Condado de Los Angeles.\n' +
        '\n' +
        'Hasta ahora contaban con un mes, el de noviembre, dedicado a celebrar su herencia y a preservar espacios de las tribus americanas originales. Esta votación supone una gran victoria para los defensores de sus derechos y su cultura, además de una medida de presión para otras partes del país donde el debate también está sobre la mesa.\n' +
        '\n' +
        'El concejal Mitch O\'Farrell, miembro de la tribu Wyandotte de Oklahoma y precursor de la medida, indicó en un escrito que esto debería enviar un mensaje a Washington "de que no hay mejor día para honrar a nuestros habitantes originales, mientras se subraya la ridiculez de celebrar una figura histórica, responsable de un sufrimiento tan profundo que todavía sienten generaciones de pueblos indígenas. Esto es más que simbólico. Es espiritual y moralmente necesario".\n' +
        '\n' +
        'Es un debate también candente en España, que celebra el 12 de octubre con un desfile militar, y que se ha encontrado con la oposición, entre otros, de la alcaldesa de Barcelona, Ada Colau, al considerar una "vergüenza" celebrar un genocidio. La CUP ha llegado a pedir la retirada de las estatuas de Colón, con indudables paralelismos a lo sucedido con el General Lee en Estados Unidos.'),
    new News(20, 'Pedraz archiva la querella contra el embajador en Kabul por el atentado en el que murieron dos policías', 'El juez de la Audiencia Nacional Santiago Pedraz ha archivado la querella contra el embajador de España en Kabul, Emilio Pérez de Agreda, admitida en noviembre de 2016 por posibles...', 'El juez de la Audiencia Nacional Santiago Pedraz ha archivado la querella contra el embajador de España en Kabul, Emilio Pérez de Agreda, admitida en noviembre de 2016 por posibles delitos de homicidio imprudente y siete en grado de tentativa por la falta de medidas de seguridad en la embajada en Afganistán en el atentado cometido el 11 de diciembre de 2015 y en el que murieron los agentes del Cuerpo Nacional de PolicíaJorge García Tudela e Isidro Gabino San Martín Hernández.\n' +
        '\n' +
        'El magistrado admitió la querella presentada por los familiares de los destinados en la sede diplomática y aceptó investigar a Pérez de Ágreda y al segundo máximo responsable de la legación, Oriol Solá, al considerar que los hechos tenían apariencia de "infracción penal". Los familiares acusan a los dos diplomáticos de no atender "nunca" las recomendaciones y peticiones de mayor seguridad para la embajada, que se remontan al inicio de su construcción, en el año 2008.\n' +
        '\n' +
        'El juez entiende que los diplomáticos no cometieron ningún delito al no ser "expertos en seguridad"\n' +
        '\n' +
        'Ahora, el titular del Juzgado Central de Instrucción número 1 concluye en un auto de apenas dos páginas [léalo en PDF] que la investigación conduce a negar la existencia de una acción concreta "omitida, intencional o imprudente" por parte de Pérez de Agreda y Solá.\n' +
        '\n' +
        'Añade que ninguno de los dos habrían llevado a cabo "ninguna acción generadora de un riesgo no permitido, ni ostentaban ni asumía la condición de garantes de que el resultado no se produjera, de forma que el desgraciado siniestro no habría podido ser evitado mediante una hipotética acción omitida".\n' +
        '\n' +
        'El juez Pedraz continúa investigando si hubo fallo de seguridad en la embajada, después de que el pasado mes de enero, la Sección Cuarta de lo Penal de la Audiencia Nacional avalase que la instrucción del atentado se diferenciase en dos partes: por un lado, el atentado como terrorismo y, por otro, la posible responsabilidad de las autoridades españolas por una falta de diligencia en la seguridad de la legación diplomática.\n' +
        '\n' +
        'Pedraz achaca al Estado la falta de medidas de seguridad\n' +
        '\n' +
        'Pedraz apunta en su auto que la embajada se encontraba fuera del espacio de seguridad de la capital afgana, "lo que suponía que la sede fuera un objetivo especialmente vulnerable frente a posibles atentados" y que, por ello, el "Estado español debió mucho antes adecuar las correspondientes medidas de seguridad".\n' +
        '\n' +
        'No obstante, el magistrado, subraya que, aunque el embajador y la segunda autoridad tienen el deber de "velar por la seguridad e integridad de los ciudadanos", no puede recaer sobre ellos ninguna responsabilidad criminal porque no son "expertos en seguridad" y "carecen de los debidos conocimientos".\n' +
        '\n' +
        '"Ni aún ante el \'aviso\' o \'alerta\' de los servicios de información franceses, dado el contenido del mismo (...) y momento en que se produce y que no permitiría a los citados diplomáticos actuar en medida alguna para evitar el resultado", dice el auto.\n' +
        '\n' +
        'Los familiares de las víctimas aseguraron en su querella que las deficiencias se comunicaron también a Exteriores y que la mañana del día en que se produjo el atentado se alertó, por los servicios secretos franceses, del riesgo de ataque. "Esto debería haber provocado la toma extraordinaria de medidas" que hubieran evitado la explosión de un coche bomba en los muros de la legación, indican.\n' +
        '\n' +
        'Las instalaciones de la embajada, con garitas de paja, ventanas de plástico y puertas de madera, no eran las adecuadas para el lugar donde se encuentra, añade la querella que destaca que la sede diplomática está, además, situada fuera del perímetro de seguridad, en un barrio "rodeado de casas de militares y de señores de la guerra".\n' +
        '\n' +
        'El domicilio del embajador -que estaba de vacaciones el día que se produjo el atentado- sí se encuentra, no obstante, en la conocida como zona verde. Pérez de Agreda mantuvo, a pesar de ello, un "mutismo absoluto" sobre estos problemas y "ponía en constante riesgo" a los ocupantes del edificio al permitir "el trasiego de mercaderes" que paseaban por la legación ofreciendo productos como joyas y alfombras, dicen los familiares.'),
    new News(21, 'El error humano de Disney con Noah', 'Leo con estupefacción la noticia de cómo Eurodisney prohibió a un niño (de nombre Noah y tres años de edad) convertirse en \'princesa por un día\'.', 'Leo con estupefacción la noticia de cómo Eurodisney prohibió a un niño (de nombre Noah y tres años de edad) convertirse en \'princesa por un día\'. La estupefacción llega porque Disney no es una marca que se mantenga retraída de las tendencias actuales. Pese a que la humanización que hace de los animales haya provocado un exceso de celo a la hora de concederles a veces los mismos derechos que a los seres humanos, Disney ha querido (con sus tiempos de macro compañía) adaptarse a la sociedad y, de hecho, no hace ni un mes que anunciaban que el próximo año presentarán a su primera princesa homosexual. Así que esa prohibición responde más a un error humano que a una directriz empresarial. Eurodisney ya pedido disculpas a la madre del pequeño.\n' +
        '\n' +
        'Los padres, a veces, tenemos problemas a la hora de explicar las relaciones humanas a nuestros hijos. Unos problemas que no provienen de ellos, nacidos sin prejuicios, si no de nosotros mismos. Venimos de una sociedad que ha tardado demasiado en reconocer los grises y eso, aunque no queramos, sigue metido en un pequeño reducto de nuestro cerebro. Mi hija es aún muy pequeña para plantearse si quiera los estereotipos de sexo. Sin embargo, cuando se prueba un vestido nuevo, corre como una centella a verse en el espejo. Le pide a su abuela que le pinte las uñas y, por supuesto, adora a las princesas de Frozen como cualquier menor de este universo.\n' +
        '\n' +
        'Pese a ello, tiene el mismo número de pelotas que de muñecas y disfruta lo mismo pateando los esféricos que sacando a \'sus bebes\' de paseo. Sinceramente, uno ni se plantea la orientación sexual de una niña de dos años pero sí le preocupa que la sociedad no lo entienda si no es la \'tradicional\' y teme que ello le suponga un problema en el futuro. Imagino que no los habrá porque ellos son el futuro y, si conseguimos que crezcan sin contaminarles su mente con estereotipos pasados, ellos romperán con ese tufo del que nosotros no nos hemos desprendido del todo.\n' +
        '\n' +
        'Recuerdo una frase de un niño en la película Poli de guardería que protagoniza Arnold Schwarzenegger (sí, la he visto y varias veces): "Los niños tienen pene y las niñas vagina". Recuerdo en cómo me hacía reír cuando era adolescente. Me reía por la inocencia del pequeño y porque su cara reflejaba que ignoraba completamente el significado de lo que decía. Casi 30 años más tarde, el autobús de Hazte Oír tomaba una frase muy similar como eslogan de su \'campaña\'. No son ellos, somos nosotros. No les contaminemos.'),
    new News(22, 'El impactante nuevo aspecto de Sylvester Stallone', 'Los fans de Sylvester Stallone, de 71 años, se han alarmado este fin de semana al ver unas imágenes en las que el actor aparece muy demacrado. ', 'En las fotografías se ve al intérprete de Rocky sin cabello y con un aspecto muy desmejorado, lo que rápidamente generó rumores sobre su estado de salud. \n Sin embargo, se trata de imágenes del rodaje de \'Creed 2\', película en la que su personaje, Rocky Balboa, lucha contra un cáncer.\n' +
        '\n' +
        'Stallone confirmó que la secuela de \'Creed\' llegará a los cines en 2018.'),
    new News(23, 'Carlos Herrera negocia con TVE su vuelta a la televisión para presentar ¿Y tú que opinas?', 'Carlos Herrera mantiene conversaciones con TVE para elaborar un nuevo programa de Entretenimiento en la cadena pública.', 'Carlos Herrera mantiene conversaciones con TVE para elaborar un nuevo programa de Entretenimiento en la cadena pública. Según ha podido confirmar EL MUNDO, no se trataría de un debate político, tal y como se rumorea, sino de participación ciudadana, aprovechando la vertiente comunicativa del periodista, conocido por su fluida relación con sus múltiples seguidores, los denominados fósforos. El programa en cuestión es ¿Y tú qué opinas?, producción aprobada por el consejo de administración de la cadena pública a finales de julio. Zebra Producciones se encargaría de realizarlo.\n' +
        '\n' +
        'El programa Arucitys ha dado la voz de alarma sobre el proyecto de Herrera para TVE. Sin embargo, fuentes conocedoras de la negociación exponen a este diario que no habría contenido político en el formato, que en todo caso se enmarcaría en el área de Entretenimiento.\n' +
        '\n' +
        'El principal escollo es obvio: la relación contractual con Cope del locutor, que comienza esta semana la temporada radiofónica. Herrera está vinculado a la cadena de la Conferencia Episcopal al menos hasta el término de esta temporada, ya firmada.\n' +
        '\n' +
        'Para Herrera sería fundamental encontrar una franja de trabajo compatible con su día a día en la emisora, en la que ha mejorado sustancialmente la audiencia: ha llegado a superar los dos millones y, según el último EGM, marca la cifra de 1.881.000. Por consiguiente, desde su fichaje desde Onda Cero se ha demostrado fundamental para Cope.\n' +
        '\n' +
        'Así se pronunció Herrera en una entrevista con este diario publicada en abril: "Cuando acabe el contrato estaré al borde de los 61 años. Ahora mismo, mi idea es una paulatina retirada a otras esferas menos en primer plano dentro del mundo de la radio. Ésa es mi idea, pero no siempre sale lo que uno quiere".'),
    new News(15, 'Nadal toma impulso ante Dolgopolov', 'Logra su victoria más convincente del torneo y entra en cuartos por primera vez desde 2013, cuando ganó el segundo de sus títulos en Flushing Meadows', 'En la más convincente de sus actuaciones en lo que va de torneo, Rafael Nadal venció a Alexandr Dolgopolov por 6-2, 6-4 y 6-1, en una hora y 42 minutos, y se metió en los cuartos de final del Abierto de Estados Unidos por primera vez desde que ganó en 2013 el segundo de sus títulos en Nueva York. Fue su victoria número 50 en esta competición. Se enfrentará el miércoles al vencedor del partido entre Goffin y Rublev, la antesala de lo que puede ser la esperadísima semifinal ante Roger Federer, un clásico aún insólito en el cuarto Grand Slam del calendario. El ucraniano presentó poca oposición. Se dejó ir en una confrontación donde sólo asomó en sus dos únicas bolas de break , frustradas ambas en el sexto juego. [Narración y estadísticas]\n' +
        '\n' +
        'A diferencia de los partidos anteriores en el torneo, Nadal tomó pronto ventaja. Rompió en el tercer juego y sentó las bases para dominar con comodidad. Dolgopolov ofrecía un retrato bastante ajustado de sí mismo, un jugador de chispazos que hacía buenas las fundadas reservas sobre su consistencia para encarar al número 1 del mundo en una cita al mejor de cinco sets. Dio la impresión de que el español había tomado buena nota de lo acontecido en las tres rondas anteriores, en las que necesitó un desempate contra Lajovic y perdió el primer parcial contra Daniel y Mayer.\n' +
        '\n' +
        'El ucraniano necesitaba bastante más que puntuales saques relampagueantes y algunos soberbios golpes de revés. Nadal exige una respuesta de máxima solidez a cualquiera de sus rivales y el que tenía frente a él carece de ella. Dolgopolov le facilitó agregar la confianza que su juego precisaba después de dubitativos inicios. Muy firme con el servicio, que no cedió en ninguna ocasión, ganando el 82% de los puntos con el primero y el 79% con el segundo, buscó a menudo el cuerpo de un adversario capaz de abrir ángulos, particularmente con el revés. La derecha fue también otro de los fundamentos del triunfo.\n' +
        '\n' +
        'Bajo su aire indolente, el tenista de Kiev invita a menudo a la distracción al otro lado de la pista. Fue una cita bien distinta a las precedentes, señalada por la genuina figura de Dolgopolov, diferente a todos. Después de ganar con facilidad el primer set, en el siguiente, sin apenas intercambios, bajo el ritmo sincopado del ucraniano, Nadal hubo de esperar al noveno juego para abrir una brecha ya muy seria en el marcador. Otra ruptura de inicio en el tercero le proyectó definitivamente hacia la victoria. No hubo alternativa. Y sí un Nadal con mejor cara, acostumbrado a crecer cuando empieza a aproximarse el reparto de premios.'),
    new News(16, 'Los vigilantes de seguridad de El Prat dicen que no se está cumpliendo el laudo y convocan otra huelga', 'En una decisión rotunda y unánime, los trabajadores de los controles de seguridad del aeropuerto de El Prat acordaron ayer la convocatoria de una nueva huelga que empezará en las instalaciones el próximo viernes 6 de octubre.', 'La nueva exigencia de los huelguistas es que se cumpla el laudo obligatorio publicado la semana anterior. «Aunque no queremos este laudo, sí pedimos que se cumpla porque es lo que se nos ha prometido», afirmó el asesor del comité de huelga de los vigilantes de Eulen en El Prat, Juan Carlos Giménez. «Nuestra situación es ahora peor que cuando empezamos», añadió.\n' +
        '\n' +
        'La plantilla considera que el laudo arbitral empeora las condiciones de la propuesta acordada por el gestor aeroportuario Aena, el Departamento de Trabajo de la Generalitat y la dirección de Eulen. «No nos gusta nada pero exigimos su cumplimiento porque estamos mucho más presionados que hace dos meses, sin prácticamente poder ausentarnos tres minutos para ir al baño», explicó un empleado.\n' +
        '\n' +
        'Con esta segunda oleada de paros, los trabajadores de la concesionaria Eulen denuncian que sus actuales condiciones de trabajo, impuestas por un árbitro designado por el Gobierno, han empeorado respecto a las que los llevó a iniciar, el pasado 24 de julio, el conflicto laboral que sumió El Prat en el caos, con largas esperas de pasajeros durante 20 días, hasta que la Guardia Civil tomó el control de los filtros.\n' +
        '\n' +
        'Giménez admitió que «es increíble» que los trabajadores exijan el cumplimiento de un laudo obligatorio contra el que ayer votaron unánimemente los 115 asistentes a una asamblea que terminó a las 18.00 horas en un equipamiento municipal de El Prat de Llobregat. «Queremos que se cumpla aquello que no queremos pero que es a lo único a lo que nos podemos acoger y que no se está cumpliendo», manifestó Giménez al término de una asamblea en la que los empleados denunciaron que su día a día es hoy «mucho peor» que al inicio de las movilizaciones.\n' +
        '\n' +
        'Con idéntica unidad, la plantilla secundó una nueva huelga en protesta contra el «incumplimiento» de todos los puntos del laudo, en concreto con los que garantizan pausas para comer o para ir al lavabo durante su jornada laboral.\n' +
        '\n' +
        'Con un mes por delante para la anunciada huelga, el comité reclama que el gestor aeroportuario Aena vuelva a sentarse en la mesa de negociación de un conflicto del que, dicen, no van «a permitir que vuelva a irse de rositas». La plantilla exige que Aena «dé soluciones» y que aporte «garantías de que va a respetar las mejoras que incluye el convenio para que algo así no pueda volver a pasar en el futuro».\n' +
        '\n' +
        'Los nuevos paros, que arrancarán el primer viernes de octubre, serán inicialmente parciales y semanales pero el comité de huelga anunció que podrán convertirse en totales y diarios. La huelga prevista para este viernes quedó desconvocada en tanto que Eulen retiró los despidos y las sanciones a los empleados, tal y como establecía el laudo.\n' +
        '\n' +
        'La plantilla se manifestará en las calles de Madrid el próximo 27 de septiembre a favor del cumplimiento del convenio nacional de vigilantes de seguridad privada.'),
    new News(17, 'Albert Rivera plantea meter en la \'nevera\' a Rajoy durante cuatro años', 'Ciudadanos mantiene el foco en Mariano Rajoy. Sus dardos parlamentarios van dirigidos a él, pero bajo el paraguas del disimulo. El partido naranja ha registrado en el Congreso su Proposición de Ley para limitar el mandato del presidente del Gobierno a ocho años...', 'Albert Rivera, presidente de la formación, ha reconocido que lo impulsaron en la negociación del pacto de investidura [lea el acuerdo en PDF] sabiendo que el PP "no va a cumplir". Para sortear la posible inconstitucionalidad, Ciudadanos ha introducido un matiz desde su propuesta inicial: se podrá ser candidato a presidente aunque se haya gobernado 8 años, si han transcurrido cuatro años. Esto es, si, por ejemplo, Rajoy se aparta una legislatura, la iniciativa de Cs le dejaría volver a ser presidente.\n' +
        '\n' +
        'Ciudadanos y PP chocan abiertamente en esta materia. El PP considera que limitar el mandato del presidente del Gobierno a ocho años requiere de una reforma de la Constitución y creen que no es el momento. La vicepresidenta del Gobierno, Soraya Sáenz de Santamaría, explicaba en la Ser, horas antes de que Rivera presentara la propuesta, que no es el momento de reformar la Carta Magna para esto, tal y como está el tema de Cataluña y con el condicionante de que Podemos exigirá un referéndum para cualquier cambio.\n' +
        '\n' +
        'La formación naranja considera que no es necesaria una reforma constitucional. Aboga por modificar la Ley del Gobierno, concretamente su artículo 11, para introducir una nueva condición de ilegibilidad: "Para ser nombrado presidente del Gobierno se requiere, además de los requisitos del apartado anterior, no haber ostentado, de manera continua, el cargo durante ocho años, salvo que, desde el agotamiento del plazo, hubiese transcurrido otro de cuatro años. El agotamiento del plazo durante el desempeño del cargo, no será causa de cese".\n' +
        '\n' +
        'Ciudadanos ha tomado como hoja de ruta para esta propuesta la modificación que hizo el Gobierno de Rajoy en 2015 en la Ley reguladora del ejercicio del alto cargo de la Administración. Consideran que así, y con la introducción de una rebaja de la firmeza con la posibilidad de volver a ser candidato pasados cuatro años, sortean cualquier atisbo de inconstitucionalidad, como les acusa el PP.\n' +
        '\n' +
        'Y, ya sin dudas, el objetivo es apartar a Rajoy, que no inhabilitarlo. "No se permiten leyes con apellidos, pero es una ley aplicable y sólo hay que mirar cuándo empezó Rajoy a ser presidente y se encontrará la fecha de cuando incurriría en incompatibilidad", ha explicado Rivera, tras la reunión de su Ejecutiva. Esto es, a finales de 2019 Rajoy no podría volver a ser, siempre que agote esta legislatura, pues la fisura en esta propuesta es que si se adelantan las urnas antes de cumplir ocho años se podría repetir.\n' +
        '\n' +
        'La idea de Cs es que la ley entre en vigor el día siguiente al de su publicación en el Boletín Oficial del Estado. Pero como ha informado este diario, la formación naranja necesita del apoyo de PSOE y Podemos para poder aprobar este cambio normativo, toda vez que el PP no está por la labor. El éxito de la iniciativa está, pues, a expensas de la decisión que tomen Pedro Sánchez y Pablo Iglesias.'),
    new News(18, 'La disuasión, la principal victoria de Kim Jong-un', 'Ni las sanciones, ni las amenazas ni el aislamiento internacional doblegan la capacidad y voluntad norcoreana de mejorar y ampliar su arsenal nuclear. ', 'Ni las sanciones, ni las amenazas ni el aislamiento internacional doblegan la capacidad y voluntad norcoreana de mejorar y ampliar su arsenal nuclear. Su sexta prueba atómica refleja la coherencia de Kim Jong-un respecto a sus promesas y advertencias, pero también una firme voluntad de obtener sus objetivos aunque arriesgue con ello el tibio apoyo de China, su protector internacional.\n' +
        '¿Qué pretende Kim Jong-un?\n' +
        '\n' +
        'Alcanzar una ambición que le consagraría como dirigente y le haría pasar a la Historia, dejándolo al nivel de su padre y su abuelo tras sólo seis años en el poder: lograr que Corea del Norte sea reconocida como potencia nuclear confirmando así su supremacía respecto al Sur, su gran competidor, y Japón. Eso disuadiría al resto de enemigos, y en especial a EEUU, a la hora de intentar reemplazar a la dinastía en el poder del país comunista.\n' +
        '\n' +
        'También confirmaría que, pese a su juventud, Kim Jong-un no es en absoluto el joven alocado descrito por Occidente sino un hombre de palabra: cuando lanzó un misil sobre Japón, la pasada semana, advirtió de que se trataba del "primer paso" de una nueva fase. Y cumplió. Kim demuestra que no lanza órdagos sino que da instrucciones, lo cual debería obligar a Occidente a recapacitar sobre la seriedad con la que se toma al líder norcoreano. La comunidad internacional le niega su condición nuclear pese a haber demostrado con creces que ha alcanzado la tecnología y los recursos para tener armas atómicas. Este ensayo es una invitación a Donald Trump para que inicie conversaciones que deriven en el reconocimiento del nuevo estatuto atómico y el final de las sanciones.\n' +
        '¿Por qué está acelerando las pruebas nucleares?\n' +
        '\n' +
        'Seguramente, para aprovechar la incoherencia demostrada por la Administración de Trump en lo que respecta a Corea del Norte. La eficaz amenaza de Kim sobre un supuesto ataque contra Guam que nunca se materializó puso en evidencia las inconsistencias del discurso del presidente norteamericano -a veces bravucón, a veces conciliador, siempre confuso- y las contradicciones en las que incurre con otros miembros de su Gobierno. El propio Steven Bannon advirtió, antes de salir de la Casa Blanca, de que no habría solución militar en Corea hasta que "alguien resuelva la ecuación de los millones de muertos" que implicarían las primeras horas de conflicto en Corea del Sur.\n' +
        '\n' +
        'Saber que las amenazas presidenciales de "fuego y furia como el mundo nunca antes ha visto" se diluyen en la nada resta relevancia a Trump y debilitan la credibilidad de Washington, principal aliado de Corea del Sur y Japón. El actual momento -Trump acaba de anunciar un aumento de tropas en Afganistán, participa en la coalición contra el IS, amenaza con retomar las sanciones a Irán y, en el plano interno lidia con las inundaciones provocadas por el huracán Harvey- aleja la posibilidad de que se deje arrastrar por una guerra en la península coreana que le acarrearía un conflicto mayúsculo con China, el único adversario internacional que puede medirse con el poderío norteamericano.'),

];