import { News } from './news';

export const NEWS: News[] = [
  new News(11, 'Rajoy subraya la falta de apoyos internacionales de los independentistas y sus divisiones internas de tal manera que esto todo mola mazo y asi podriamos seguir hasta el fin de los tiempos ', 'Excerpt 1', '\n' +
      '\n' +
      'El proceso legal que pretenden impulsar esta semana los independentistas catalanes para organizar el referéndum del 1 de octubre “no se ha producido nunca en España desde 1977, cuando recuperamos las libertades democráticas”. Así ha analizado Mariano Rajoy que Junts pel Sí apueste por tramitar este miércoles en el Parlament la Ley con la que quiere organizar una consulta que el presidente ha definido como “ilegal”. Además, el líder del PP, que mantiene un diálogo constante con Pedro Sánchez (PSOE) y Albert Rivera (Ciudadanos), ha subrayado la falta de apoyos internacionales de los soberanistas y sus divisiones internas, y ha tildado la situación de "disparate".\n' +
      '\n' +
      '“Sabían, hace mucho tiempo, que yo no iba a autorizar el referéndum, porque no podía, porque no quería, y porque se lo dije con meridiana claridad”, ha dicho el líder del PP durante la reunión de la Junta directiva nacional de su partido. “No les importó”, ha continuado. “Siguieron con su camino hacia ninguna parte. Sabían que nadie los iba a apoyar en Europa, nadie, como así ha sido. Ni en Europa ni en ningún país del mundo”, ha subrayado Rajoy. “A pesar de esto, siguieron con una huida hacia ninguna parte. Todos desconfían unos de otros, no hay nadie capaz de ejercer un liderazgo y decir que lo más razonable es rectificar”, ha seguido. “Todo esto, y ya llevamos algunos años, ha servido para dividir como nunca a la sociedad catalana y para que tengan como nunca una fuerza en Cataluña los más extremista de los extremistas”, ha lamentado. Y ha ejemplificado: “Que la Cup exigiera la cabeza de Artur Mas y se le diera es un disparate, y que ahora se le deje dirigir el Gobierno es un disparate mayor”.\n' +
      '\n' +
      'En cuanto sean tramitadas, el Gobierno recurrirá ante el Tribunal Constitucional la Ley de transitoriedad y la Ley del referéndum. Al tiempo, el Ejecutivo recuerda que los políticos independentistas que las firmen se arriesgan a ser inhabilitados. El procedimiento con el que se pretende aprobar esos textos, ha dicho Rajoy “no se ha producido nunca desde que recuperamos las libertades democráticas”.\n' +
      '\n' +
      '“Ahora continúan los despropósitos”, ha opinado Rajoy. “No pueden hacer un referéndum porque no tienen la competencia para hacerlo”, ha seguido. “Pretenden decir que pueden hacerlo ahora porque han hecho una ley, la del referéndum, que no está calificad por la Mesa, que no va en el orden del día del pleno del Parlament, sin que haya tiempo para aprobarla y que sería ilegal aunque lo hicieran”, ha recalcado. “Lo que pretenden es en un día calificar la ley, meterla en el orden del día, no aceptar las enmiendas de la oposición, ni que vayan al consejo de garantías… y además se pretende aprobarlo en ese día”, ha seguido. Y ha lamentado, en referencia a Carles Puigdemont: “Eso no se ha producido nunca desde que recuperamos las libertades democráticas. Ese es el legado que algunos van a dejar de su actividad política”.\n'),
  new News(12, 'El paro sube en agosto en 46.400 personas con el fin del empleo de verano', 'Excerpt 2', 'Content 2'),
  new News(13, 'News 3', 'Excerpt 3', 'Content 3'),
  new News(14, 'News 4', 'Excerpt 4', 'Content 4'),
  new News(15, 'News 5', 'Excerpt 5', 'Content 5')
];